name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.YOUR_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.YOUR_PASSWORD }}
          POSTGRES_DB: ${{ secrets.YOUR_DB_NAME }}

    env:
      YOUR_USERNAME: ${{ secrets.YOUR_USERNAME }}
      YOUR_PASSWORD: ${{ secrets.YOUR_PASSWORD }}
      YOUR_DB_NAME: ${{ secrets.YOUR_DB_NAME }}
      LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
      DOCKER_PORT: ${{ secrets.DOCKER_PORT }}
      LOCAL_POSTGRESQL_PORT: ${{ secrets.LOCAL_POSTGRESQL_PORT }}
      DOCKER_POSTGRESQL_PORT: ${{ secrets.DOCKER_POSTGRESQL_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build the project
        run: ./mvnw clean package

      - name: Build and push Docker images
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for DB to be ready..."
          while ! nc -z localhost ${{ secrets.LOCAL_POSTGRESQL_PORT }}; do
            sleep 1
          done
          echo "DB is ready"

      - name: Run Spring Boot tests
        run: ./mvnw test

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down